# Generated by Django 5.0.6 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlead',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
